nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/oauth/v2/auth':
            allow_origin: ['*']
            allow_headers: ['authorization']
            allow_methods: ['GET']
            allow_credentials: true
            max_age: 3600
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600