api_clients:
    resource: "@ApiBundle/Resources/config/routing/oauth.yml"
    prefix:   /oauth/v2

api:
    resource: "@ApiBundle/Resources/config/routing/api.yml"
    prefix:   /api

homepage:
    path: /
    defaults: { _controller: ApiBundle:Default:index }
