api_user_security_login:
    path: /oauth/v2/auth_login
    defaults: { _controller: ApiBundle:Security:login }

api_user_security_check:
    path: /oauth/v2/auth_login_check
    defaults: { _controller: ApiBundle:Security:check }

api_user_oauth_blank:
    path: /oauth/v2/auth_blank
    defaults: { _controller: ApiBundle:Security:blank }

api_user_oauth_receiver:
    path: /oauth/v2/auth_receiver
    defaults: { _controller: ApiBundle:Security:receiver }

api_user_security_logout:
    path: /oauth/v2/auth_logout
    defaults: { _controller: ApiBundle:Security:logout }

homepage:
    path: /
    defaults: { _controller: ApiBundle:Default:index }

api_user_login_status:
    path: /oauth/v2/auth_login_status
    defaults: { _controller: ApiBundle:Security:loginStatus }


api_user_profile:
    path: api/profile
    defaults: { _controller: ApiBundle:User:profile }

api_user_profile_clients:
    path: api/profile/clients
    defaults: { _controller: ApiBundle:User:clients }