api_activities_index:
    path: /
    methods: GET
    defaults: { _controller: ApiBundle:Activities:index }

api_activities_get:
    path: /{id}
    methods: GET
    defaults: { _controller: ApiBundle:Activities:get }