api_user_profile:
    path: api/profile
    defaults: { _controller: ApiBundle:User:profile }

api_client:
    resource: "@ApiBundle/Resources/config/routing/api/client.yml"
    prefix:   /clients

api_activities:
    resource: "@ApiBundle/Resources/config/routing/api/activities.yml"
    prefix:   /activities
